module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    ADMIN_COLLECTION:'admin',
    ORDER_COLLECTION:'order',
    WISH_LIST_COLLECTION:'wishlist',
    BANNER_COLLECTION:'banner',
    COUPON_COLLECTION:'coupon',
    ADRESS_COLLECTION:'address'
}